# Generated by Django 5.1.6 on 2025-03-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("assunto", models.CharField(max_length=50)),
                ("mensagem", models.TextField()),
                ("empresa", models.CharField(blank=True, max_length=50, null=True)),
                ("data_msg", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
